# Generated by Django 4.1.7 on 2023-03-03 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indicativos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Nomes',
            },
        ),
    ]
