# Generated by Django 4.1.7 on 2023-03-03 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicativo', '0002_alter_indicativos_options_radioamador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicativos',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
