# Generated by Django 4.1.7 on 2023-03-11 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicativo', '0003_alter_indicativos_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('indicativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicativo.indicativos')),
            ],
            options={
                'verbose_name_plural': 'Conversas',
            },
        ),
    ]
