# Generated by Django 4.1.7 on 2023-03-12 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicativo', '0004_conversa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversa',
            name='indicativo',
        ),
    ]
